FROM ewolff/docker-java
ADD target/microservice-consul-demo-turbine-server-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-consul-demo-turbine-server-0.0.1-SNAPSHOT.jar
EXPOSE 8989