version: '2'
services:
  consul:
    image: consul:v0.6.4
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  customer:
    build: ../microservice-consul-demo/microservice-consul-demo-customer
    links:
     - consul
  catalog:
    build: ../microservice-consul-demo/microservice-consul-demo-catalog
    links:
     - consul
  order:
    build: ../microservice-consul-demo/microservice-consul-demo-order
    links:
     - consul
  apache:
    build: apache
    links:
     - consul
    depends_on:
     - consul
    ports:
     - "8080:80"
  turbine:
    build: ../microservice-consul-demo/microservice-consul-demo-turbine-server
    links:
     - consul
    ports:
      - "8989:8989"


